services:
  - type: web
    name: breast-cancer-detector
    env: python
    plan: free
    runtime: python
    pythonVersion: 3.11
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
